"""add active to users

Revision ID: 28cd67e09048
Revises: 6d5ceeb22c1c
Create Date: 2026-02-22 08:44:19.346600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cd67e09048'
down_revision: Union[str, Sequence[str], None] = '6d5ceeb22c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('audio', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionary', 'audio')
    # ### end Alembic commands ###
