"""audio column deleted from dictionary

Revision ID: 83ff03e008d3
Revises: 28cd67e09048
Create Date: 2026-02-22 09:41:57.840293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83ff03e008d3'
down_revision: Union[str, Sequence[str], None] = '28cd67e09048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionary', 'audio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary', sa.Column('audio', mysql.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
